#!/usr/bin/env bash

# super simple ukrainian-flag bash script

# user=${USER:-$(id -un)}
# hostname=${HOSTNAME:-${hostname:-$(hostname)}}

block=███████████████████████████████
run() {
  for i in $(seq 0 $1); do echo "$(tput setaf 4)$block"; done
  for i in $(seq 0 $1); do echo "$(tput setaf 3)$block"; done
  tput sgr0
}

case $1 in
  -m) run 4 && figlet -f moscow 'SLAVA'$'\n''UKRAINE' | sed 's/#/█/g' ;;
  -h) echo "${0##*/} usage: [-m]" ;;
  *) block=${block}$block run 8 ;;
esac
